### PR TITLE
feat: Use RPITIT instead of Box<dyn ...>

### PR DESCRIPTION
**Pull request by mlgiraud**
Just a small PR to replace Box<dyn ...> with RPITIT, since it is now stable. I believe this is what your todo in the trait was for?

### CODE REVIEW

**Comment by mlgiraud** [comment]
Maybe it would also make sense to return a type that implements the `Error` trait, instead of something that just implements  `Debug`?

**Comment by mlgiraud** [comment]
Another question maybe: Why does the fetch function have to take a mutable reference to self? Shouldn't this be an immutable function?

**Comment by mlgiraud** [comment]
@zesterer Any updates on this?

**Comment by zesterer** [comment]
Thanks for the PR. Sorry, it got lost in my notifications. I think this is a positive change, although I'm surprised it's been stable for so long already: I'm used to things like this being nightly-only for a while!

**Pull request merged**
