### PR TITLE
Support more newlines

### PR DESCRIPTION
**Pull request by TRCYX**
Corresponds to Section 5.8 of the Unicode Standard, as well as `chumsky::text::newline`.

### CODE REVIEW

**Comment by zesterer** [comment]
Thanks! Any chance of a few tests that include these cases? This seems like code that's easy to accidentally break.

**Comment by TRCYX** [comment]
Where should I put them? In `examples` or as cargo tests?

**Comment by zesterer** [comment]
I think a unit test at the bottom of the same file would be fine, like:

```rs
#[cfg(test)]
mod tests {
    #[test]
    fn foo() {
        ...
    }
}
```

**Comment by TRCYX** [comment]
Thanks for the idea of tests. The original code was wrong in the `len` field of a `Line` ending with CRLF, neglecting the LF. To solve this problem the code becomes considerably uglier :)

**Comment by TRCYX** [comment]
Tests are added and I force-pushed to keep the history clean.

**Comment by zesterer** [comment]
> Thanks for the idea of tests. The original code was wrong in the `len` field of a `Line` ending with CRLF, neglecting the LF. To solve this problem the code becomes considerably uglier :)

Hehe, I suspected as much. Logic like this is often surprisingly difficult to get right. I feel much more comfortable merging this with tests!

**Pull request merged**
